import "oaidl.idl";
import "ocidl.idl";

[
    // 修正点：去掉了所有的 0x 前缀，保留纯十六进制字符和连字符
    uuid(2cdd8e9d-7183-4900-a818-6a75b3eec6f6), 
    version(1.0),
    helpstring("MyRpcInterface 1.0")
]
interface mgr
{
    // 测试函数：无参数，无返回值
    // 用于测试连通性，如果服务端有此函数或兼容占位，即可通过
	int MgrFunction0();
    int MgrFunction1(int  a1,int * a2);
	int MgrFunction2(int  a1,int  a2);
	int MgrFunction3(int  a1,int  a2);
}